apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cqwf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cqwf
    app.kubernetes.io/part-of: tkwch-fix-0075-0063-app
  name: devfile-sample-cqwf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cqwf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cqwf
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0063-tenant/tkwch-fix-0075-0063-app/devfile-sample-cqwf@sha256:774f62bc7071e5b9a436b359a1844c4b7b243910a26736c5b6bc069ff72c6721
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
